'use client';

import { useState, useEffect, useRef, useCallback, useMemo } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import ConnectionsTab from '@/components/ConnectionsTab';
import { 
  Mail, 
  Settings, 
  Send, 
  Users, 
  TrendingUp, 
  Clock, 
  MessageSquare,
  Bot,
  FileText,
  Sparkles,
  Zap,
  Target,
  CheckCircle,
  AlertCircle,
  RefreshCw,
  Eye,
  ExternalLink,
  Link as LinkIcon,
  Globe,
  BarChart3,
  Wrench,
  Volume2,
  VolumeX,
  Filter,
  Inbox,
  Shield,
  Building,
  MessageCircle,
  Phone,
  Archive,
  X,
  BookOpen,
  Power,
  Brain,
  Info,
  UserCheck,
  Play,
  Pause,
  Square,
  Calendar,
  DollarSign,
  TrendingDown,
  Activity
} from 'lucide-react';

export default function CompleteEmailSystem() {
  const router = useRouter();
  const [activeTab, setActiveTab] = useState('dashboard');
  const refreshIntervalRef = useRef(null);
  const autoPollIntervalRef = useRef(null);
  
  const businessProfileRef = useRef({
    name: '',
    industry: '',
    expertise: ''
  });
  
  const knowledgeBaseRef = useRef('');
  
  // ðŸŽ¯ ADDED: Preview state and ref for the textarea
  const [showingPreview, setShowingPreview] = useState(false);
  const [previewResponse, setPreviewResponse] = useState(null); // original for Reset
  const [editedResponse, setEditedResponse] = useState(''); // controlled textarea value
  const [generatingPreview, setGeneratingPreview] = useState(false);
  const previewTextareaRef = useRef(null);
  
  // ðŸŽ¯ UNIFIED: Single auto-poll state that controls everything
  // FIXED: Set interval to 30 seconds permanently
  const [autoPollStatus, setAutoPollStatus] = useState({
    isRunning: false,
    isEnabled: false,
    lastPoll: null,
    interval: 30, // Fixed at 30 seconds
    totalEmailsProcessed: 0,
    totalResponsesSent: 0
  });
  
  const [conversations, setConversations] = useState([]);
  const [gmailEmails, setGmailEmails] = useState([]);
  const [outlookEmails, setOutlookEmails] = useState([]);
  const [selectedConversation, setSelectedConversation] = useState(null);
  const [selectedGmailEmail, setSelectedGmailEmail] = useState(null);
  const [selectedOutlookEmail, setSelectedOutlookEmail] = useState(null);
  const [newMessage, setNewMessage] = useState('');
  const [loading, setLoading] = useState(true);
  const [gmailLoading, setGmailLoading] = useState(false);
  const [responding, setResponding] = useState(false);
  const [gmailConnection, setGmailConnection] = useState(null);
  const [lastRefresh, setLastRefresh] = useState(new Date());
  const [saving, setSaving] = useState(false);
  const [reconnecting, setReconnecting] = useState(false);
  const [needsReconnect, setNeedsReconnect] = useState(false);
  
  const [testResult, setTestResult] = useState(null);
  const [testing, setTesting] = useState(false);

  const [activeEmailView, setActiveEmailView] = useState('inbox');
  const [sentEmails, setSentEmails] = useState([]);
  
  // UPDATED STATS - Only the 4 metrics you want
  const [stats, setStats] = useState({
    totalResponsesSent: 0,      // AI Responses Sent
    totalLeadsCaptured: 0,      // Leads Captured
    meetingsBooked: 0,          // Meetings Booked
    avgResponseTimeMinutes: 0   // Response Time
  });

  const formatTime = (minutes) => {
    if (!minutes || minutes === 0) return '0m';
    if (minutes < 60) return `${Math.round(minutes)}m`;
    const hours = Math.floor(minutes / 60);
    const mins = Math.round(minutes % 60);
    return mins > 0 ? `${hours}h ${mins}m` : `${hours}h`;
  };

  const [dashboardSettings, setDashboardSettings] = useState({
    autoRefresh: true,
    refreshInterval: 30
  });

  // ðŸŽ¯ SIMPLIFIED: AI settings without the conflicting toggle
  const [aiSettings, setAiSettings] = useState({
    communicationTone: 'professional',
    knowledgeBase: '',
    hotLeadKeywords: ['urgent', 'asap', 'budget', 'ready'],
    customInstructions: '',
    aiModel: 'gpt-4o-mini',
    creativity: 0.7,
    responseLength: 'medium',
    behaviors: {
      hotLeadAlerts: true,
      smsLeadAlerts: false
    }
  });

  const [automationSettings, setAutomationSettings] = useState({
    emailFiltering: {
      autoArchiveSpam: true,
      blockMassEmails: true,
      personalOnly: false,
      skipAutoGenerated: true
    },
    businessRules: {
      blacklist: [],
      whitelist: [],
      customKeywords: []
    }
  });

  const [newBlacklistItem, setNewBlacklistItem] = useState('');
  const [newWhitelistItem, setNewWhitelistItem] = useState('');
  const [newCustomKeyword, setNewCustomKeyword] = useState('');

  // ðŸŽ¯ ADDED: Handle preview generation
  const handlePreviewAIResponse = async (emailId) => {
    if (!gmailConnection) return;
    
    setGeneratingPreview(true);
    setShowingPreview(false);
    setPreviewResponse(null);
    
    try {
      console.log('ðŸš€ Generating AI preview for email:', emailId);
      
      const response = await fetch('/api/gmail/monitor', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action: 'respond',
          emailAddress: gmailConnection.email,
          emailId: emailId,
          actualSend: false  // Preview only
        })
      });

      if (response.ok) {
        const data = await response.json();
        const generatedResponse = data.response || data.aiResponse || 'No response generated';
        setPreviewResponse(generatedResponse); // keep original for Reset button
        setEditedResponse(generatedResponse);  // controlled textarea value
        setShowingPreview(true);
        return data;
      }
    } catch (error) {
      console.error('âŒ Error generating preview:', error);
      alert('Failed to generate preview. Please try again.');
    } finally {
      setGeneratingPreview(false);
    }
  };

  // ðŸŽ¯ ADDED: Send edited response
  const sendEditedResponse = async () => {
    if (!gmailConnection || !selectedGmailEmail) return;

    if (!editedResponse.trim()) {
      alert('Please enter a response message');
      return;
    }
    
    setResponding(true);
    try {
      console.log('ðŸš€ Sending edited response:', editedResponse);
      
      const response = await fetch('/api/gmail/monitor', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action: 'respond',
          emailAddress: gmailConnection.email,
          emailId: selectedGmailEmail.id,
          actualSend: true,
          customResponse: editedResponse  // Send the edited text
        })
      });

      if (response.ok) {
        const data = await response.json();
        console.log('âœ… Response sent successfully');
        
        // Add to sent emails
        const sentEmail = {
          id: `sent-${Date.now()}-${selectedGmailEmail.id}`,
          originalEmailId: selectedGmailEmail.id,
          to: selectedGmailEmail.fromEmail || 'unknown@example.com',
          toName: selectedGmailEmail.fromName || selectedGmailEmail.fromEmail || 'Unknown',
          originalSubject: selectedGmailEmail.subject || 'No Subject',
          response: editedResponse,
          sentTime: new Date().toLocaleString(),
          timestamp: new Date(),
          status: 'sent'
        };
        
        setSentEmails(prev => [sentEmail, ...prev]);
        
        // Update stats - increment responses sent
        setStats(prev => ({
          ...prev,
          totalResponsesSent: prev.totalResponsesSent + 1
        }));
        
        // Hide preview and switch to sent tab
        setShowingPreview(false);
        setPreviewResponse(null);
        setTimeout(() => {
          setActiveEmailView('sent');
          checkGmailEmails(false);
        }, 500);
        
        alert('âœ… Response sent successfully!');
      } else {
        throw new Error('Failed to send response');
      }
    } catch (error) {
      console.error('âŒ Error sending response:', error);
      alert('Failed to send response. Please try again.');
    } finally {
      setResponding(false);
    }
  };

  // ðŸŽ¯ UNIFIED: Toggle that controls both auto-polling AND AI responses
  const toggleAutoPoll = useCallback(async () => {
    const newState = !autoPollStatus.isRunning;
    const newEnabled = !autoPollStatus.isEnabled;
    
    console.log(`ðŸ”„ Toggling Auto-Poll: ${newState ? 'ON' : 'OFF'}`);
    console.log(`ðŸ¤– AI Responses will be: ${newEnabled ? 'ENABLED' : 'DISABLED'}`);
    
    // Update local state immediately for responsive UI
    setAutoPollStatus(prev => ({ 
      ...prev, 
      isRunning: newState,
      isEnabled: newEnabled
    }));
    
    // Save to database
    setSaving(true);
    try {
      // ðŸŽ¯ UPDATED: Use the new save endpoint for business rules
      const response = await fetch('/api/email-settings/save', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          enable_ai_responses: newEnabled,
          tone: aiSettings.communicationTone,
          ai_model: aiSettings.aiModel,
          response_length: aiSettings.responseLength,
          custom_instructions: aiSettings.customInstructions,
          knowledge_base: knowledgeBaseRef.current,
          expertise: businessProfileRef.current.industry,
          specialties: businessProfileRef.current.expertise,
          hot_lead_keywords: aiSettings.hotLeadKeywords,
          alert_hot_leads: aiSettings.behaviors.hotLeadAlerts,
          sms_lead_alerts: aiSettings.behaviors.smsLeadAlerts,
          ai_temperature: aiSettings.creativity,
          ai_max_tokens: 500,
          auto_archive_spam: automationSettings.emailFiltering.autoArchiveSpam,
          block_mass_emails: automationSettings.emailFiltering.blockMassEmails,
          personal_only: automationSettings.emailFiltering.personalOnly,
          skip_auto_generated: automationSettings.emailFiltering.skipAutoGenerated,
          blacklist_emails: automationSettings.businessRules.blacklist,
          whitelist_emails: automationSettings.businessRules.whitelist,
          priority_keywords: automationSettings.businessRules.customKeywords
        })
      });

      if (response.ok) {
        console.log('âœ… AI settings saved successfully');
        
        if (newState) {
          // Start polling
          if (autoPollIntervalRef.current) {
            clearInterval(autoPollIntervalRef.current);
          }
          
          // Fixed 30 second interval
          const effectiveInterval = 30;
          console.log('ðŸš€ Starting auto-poll with interval:', effectiveInterval, 'seconds');
          
          // Delay first run by 3 seconds
          setTimeout(() => {
            runAutoPoll();
          }, 3000);
          
          // Set up interval
          autoPollIntervalRef.current = setInterval(() => {
            runAutoPoll();
          }, effectiveInterval * 1000);
        } else {
          // Stop polling
          console.log('ðŸ›‘ Stopping auto-poll');
          if (autoPollIntervalRef.current) {
            clearInterval(autoPollIntervalRef.current);
            autoPollIntervalRef.current = null;
          }
        }
      } else {
        throw new Error('Failed to save settings');
      }
    } catch (error) {
      console.error('âŒ Error saving settings:', error);
      // Revert on error
      setAutoPollStatus(prev => ({ 
        ...prev, 
        isRunning: !newState,
        isEnabled: !newEnabled
      }));
      alert('Failed to save settings. Please try again.');
    } finally {
      setSaving(false);
    }
  }, [autoPollStatus, aiSettings, automationSettings]);

  // ðŸŽ¯ FIXED: Client-side auto-poll that calls monitor API directly
  const runAutoPoll = useCallback(async () => {
    if (!gmailConnection?.email) return;
    
    console.log('ðŸ”„ Running auto-poll cycle...');
    
    try {
      // Step 1: Check for emails directly (not through auto-poll API)
      console.log('ðŸ“¬ Checking for new emails...');
      
      const checkResponse = await fetch('/api/gmail/monitor', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action: 'check',
          emailAddress: gmailConnection.email
        })
      });

      if (!checkResponse.ok) {
        console.error('âŒ Monitor check failed:', checkResponse.status);
        return;
      }

      const emailData = await checkResponse.json();
      const emails = emailData.emails || [];
      console.log('ðŸ“Š Found', emails.length, 'emails');
      
      // Update the email list in UI
      setGmailEmails(emails);
      
      // Step 2: If enabled and we have emails, send AI responses
      if (autoPollStatus.isEnabled && emails.length > 0) {
        console.log('ðŸ¤– Processing emails with AI responses...');
        
        // Process up to 2 emails at a time
        const emailsToProcess = emails.slice(0, 2);
        let responsesGenerated = 0;
        
        for (let i = 0; i < emailsToProcess.length; i++) {
          const email = emailsToProcess[i];
          console.log(`ðŸ“§ Processing email ${i + 1}: "${email.subject}"`);
          
          try {
            const respondResponse = await fetch('/api/gmail/monitor', {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({
                action: 'respond',
                emailAddress: gmailConnection.email,
                emailId: email.id,
                actualSend: true
              })
            });

            if (respondResponse.ok) {
              const responseData = await respondResponse.json();
              if (responseData.success) {
                responsesGenerated++;
                console.log(`âœ… AI response sent for email ${i + 1}`);
                
                // Add to sent emails list
                const sentEmail = {
                  id: `sent-${Date.now()}-${email.id}`,
                  originalEmailId: email.id,
                  to: email.fromEmail || 'unknown@example.com',
                  toName: email.fromName || email.fromEmail || 'Unknown',
                  originalSubject: email.subject || 'No Subject',
                  response: responseData.response || responseData.aiResponse || 'Response sent',
                  sentTime: new Date().toLocaleString(),
                  timestamp: new Date(),
                  status: 'sent'
                };
                
                setSentEmails(prev => [sentEmail, ...prev]);
                
                // Update stats
                setStats(prev => ({
                  ...prev,
                  totalResponsesSent: prev.totalResponsesSent + 1
                }));
              } else {
                console.log(`âš ï¸ Response not sent for email ${i + 1}:`, responseData.error);
              }
            } else {
              console.error(`âŒ Failed to respond to email ${i + 1}:`, respondResponse.status);
            }
            
            // Wait 1 second between responses
            if (i < emailsToProcess.length - 1) {
              await new Promise(resolve => setTimeout(resolve, 1000));
            }
          } catch (err) {
            console.error(`âŒ Failed to respond to email ${i + 1}:`, err);
          }
        }
        
        // Update counters
        setAutoPollStatus(prev => ({
          ...prev,
          lastPoll: new Date(),
          totalEmailsProcessed: prev.totalEmailsProcessed + emails.length,
          totalResponsesSent: prev.totalResponsesSent + responsesGenerated
        }));
        
        console.log(`ðŸŽ‰ Auto-poll completed: ${responsesGenerated} responses sent`);
      } else {
        // Just update the last poll time
        setAutoPollStatus(prev => ({
          ...prev,
          lastPoll: new Date(),
          totalEmailsProcessed: prev.totalEmailsProcessed + emails.length
        }));
        
        console.log('ðŸ”­ No emails to process or AI disabled');
      }
      
      // Refresh the UI
      setLastRefresh(new Date());
      
    } catch (error) {
      console.error('âŒ Auto-poll error:', error);
    }
  }, [gmailConnection?.email, autoPollStatus.isEnabled]);

  // Stop auto-poll function
  const stopAutoPoll = useCallback(() => {
    console.log('ðŸ›‘ Stopping auto-poll');
    
    if (autoPollIntervalRef.current) {
      clearInterval(autoPollIntervalRef.current);
      autoPollIntervalRef.current = null;
    }
    
    setAutoPollStatus(prev => ({ ...prev, isRunning: false }));
  }, []);

  const handleAiBehaviorChange = useCallback((field, value) => {
    setAiSettings(prev => ({
      ...prev,
      behaviors: { ...prev.behaviors, [field]: value }
    }));
  }, []);

  const handleEmailFilteringChange = useCallback((field, value) => {
    setAutomationSettings(prev => ({
      ...prev,
      emailFiltering: { ...prev.emailFiltering, [field]: value }
    }));
  }, []);

  const tabs = useMemo(() => [
    { 
      id: 'dashboard', 
      label: 'Dashboard', 
      icon: BarChart3,
      description: 'Real-time Gmail conversations and AI responses'
    },
    {
      id: 'automation', 
      label: 'Automation', 
      icon: Wrench,
      description: 'Email filtering rules and business controls'
    },
    { 
      id: 'connections', 
      label: 'Connections', 
      icon: Settings,
      description: 'Manage Gmail and domain email connections'
    }
  ], []);

  useEffect(() => {
    loadInitialData();
    handleUrlParameters();
  }, []);

  const handleUrlParameters = () => {
    const urlParams = new URLSearchParams(window.location.search);
    const tab = urlParams.get('tab');
    const success = urlParams.get('success');
    const error = urlParams.get('error');
    
    console.log('ðŸ” URL Parameters:', { tab, success, error });
    
    if (tab && tabs.some(t => t.id === tab)) {
      console.log('ðŸŽ¯ Setting active tab to:', tab);
      setActiveTab(tab);
    }
    
    if (success === 'gmail_connected') {
      console.log('âœ… Gmail connection successful');
    }
    
    if (error) {
      console.log('âŒ OAuth error:', error);
    }
    
    if (tab || success || error) {
      const newUrl = window.location.pathname;
      window.history.replaceState({}, document.title, newUrl);
      console.log('ðŸ§¹ Cleaned URL parameters');
    }
  };

  useEffect(() => {
    console.log('ðŸ“Š Sent emails state changed:', sentEmails);
  }, [sentEmails]);

  useEffect(() => {
    if (refreshIntervalRef.current) {
      clearInterval(refreshIntervalRef.current);
      refreshIntervalRef.current = null;
    }

    if (activeTab === 'dashboard' && gmailConnection && !loading && !autoPollStatus.isRunning) {
      refreshIntervalRef.current = setInterval(() => {
        checkGmailEmails(true);
        setLastRefresh(new Date());
      }, dashboardSettings.refreshInterval * 1000);
    }

    return () => {
      if (refreshIntervalRef.current) {
        clearInterval(refreshIntervalRef.current);
        refreshIntervalRef.current = null;
      }
    };
  }, [activeTab, gmailConnection?.email, dashboardSettings.refreshInterval, loading, autoPollStatus.isRunning]);

  useEffect(() => {
    return () => {
      if (autoPollIntervalRef.current) {
        clearInterval(autoPollIntervalRef.current);
      }
    };
  }, []);

  const loadInitialData = async () => {
    setLoading(true);
    try {
      await Promise.all([
        loadEmailData(),
        checkGmailConnection(),
        loadAISettings(),
        loadEmailSettings(),
        fetchOutlookEmails(),
      ]);
    } catch (error) {
      console.error('Error loading initial data:', error);
    } finally {
      setLoading(false);
    }
  };

  const loadEmailData = async () => {
    try {
      const convResponse = await fetch('/api/customer/email-conversations');
      if (convResponse.ok) {
        const convData = await convResponse.json();
        setConversations(convData.conversations || []);
      }

      const statsResponse = await fetch('/api/customer/email-stats');
      if (statsResponse.ok) {
        const statsData = await statsResponse.json();
        if (statsData.success && statsData.stats) {
          // Map to our simplified 4 metrics
          setStats({
            totalResponsesSent: statsData.stats.totalResponsesSent || autoPollStatus.totalResponsesSent || 0,
            totalLeadsCaptured: statsData.stats.totalLeadsCaptured || 0,
            meetingsBooked: statsData.stats.meetingsBooked || 0,
            avgResponseTimeMinutes: statsData.stats.avgResponseTimeMinutes || 0
          });
        }
      }
    } catch (error) {
      console.error('Error loading email data:', error);
    }
  };

  const checkGmailConnection = async () => {
    try {
      const response = await fetch('/api/gmail/status');
      if (response.ok) {
        const data = await response.json();
        
        if (data.connected && data.connection) {
          setGmailConnection(data.connection);
        } else {
          setGmailConnection(null);
        }
      }
    } catch (error) {
      console.error('Error checking Gmail connection:', error);
      setGmailConnection(null);
    }
  };

  const loadAISettings = async () => {
    try {
      const response = await fetch('/api/customer/ai-settings');
      if (response.ok) {
        const data = await response.json();
        if (data.settings) {
          businessProfileRef.current = {
            name: data.customer?.business_name || '',
            industry: data.settings.expertise || '',
            expertise: data.settings.specialties || ''
          };
          
          knowledgeBaseRef.current = data.settings.knowledge_base || '';
          
          // ðŸŽ¯ IMPORTANT: Load the enabled state from database
          const isEnabled = data.settings.enable_ai_responses !== false;
          setAutoPollStatus(prev => ({
            ...prev,
            isEnabled: isEnabled
          }));
          
          setAiSettings(prev => ({
            ...prev,
            communicationTone: data.settings.tone || 'professional',
            knowledgeBase: data.settings.knowledge_base || '',
            customInstructions: data.settings.custom_instructions || data.settings.ai_system_prompt || '',
            aiModel: data.settings.ai_model || 'gpt-4o-mini',
            creativity: parseFloat(data.settings.ai_temperature) || 0.7,
            responseLength: data.settings.response_length || 'medium',
            behaviors: {
              hotLeadAlerts: data.settings.alert_hot_leads !== false,
              smsLeadAlerts: data.settings.sms_lead_alerts === true
            }
          }));

          if (data.settings.hot_lead_keywords) {
            setAiSettings(prev => ({
              ...prev,
              hotLeadKeywords: Array.isArray(data.settings.hot_lead_keywords) 
                ? data.settings.hot_lead_keywords 
                : prev.hotLeadKeywords
            }));
          }
        }
      } else if (response.status === 404) {
        console.log('AI settings API not found - using defaults');
      }
    } catch (error) {
      console.log('AI settings not available - using defaults');
    }
  };

  // ðŸŽ¯ NEW: Load email settings (business rules) separately
  const loadEmailSettings = async () => {
    try {
      const response = await fetch('/api/email-settings/save', {
        method: 'GET'
      });
      
      if (response.ok) {
        const data = await response.json();
        if (data.settings) {
          // Load blacklist/whitelist/priority keywords
          setAutomationSettings(prev => ({
            ...prev,
            emailFiltering: {
              autoArchiveSpam: data.settings.auto_archive_spam !== false,
              blockMassEmails: data.settings.block_mass_emails !== false,
              personalOnly: data.settings.personal_only || false,
              skipAutoGenerated: data.settings.skip_auto_generated !== false
            },
            businessRules: {
              blacklist: data.settings.blacklist_emails || [],
              whitelist: data.settings.whitelist_emails || [],
              customKeywords: data.settings.priority_keywords || []
            }
          }));
          
          console.log('âœ… Loaded email settings with business rules');
        }
      }
    } catch (error) {
      console.error('Error loading email settings:', error);
    }
  };

  // ðŸŽ¯ UPDATED: Save all settings using the new endpoint
  const saveAllSettings = async () => {
    setSaving(true);
    try {
      // Prepare all settings for saving
      const settingsToSave = {
        // AI Response settings
        enable_ai_responses: autoPollStatus.isEnabled,
        tone: aiSettings.communicationTone,
        expertise: businessProfileRef.current.industry,
        specialties: businessProfileRef.current.expertise,
        knowledge_base: knowledgeBaseRef.current,
        custom_instructions: aiSettings.customInstructions,
        ai_system_prompt: aiSettings.customInstructions,
        ai_model: aiSettings.aiModel,
        ai_temperature: aiSettings.creativity,
        ai_max_tokens: 500,
        response_length: aiSettings.responseLength,
        alert_hot_leads: aiSettings.behaviors.hotLeadAlerts,
        sms_lead_alerts: aiSettings.behaviors.smsLeadAlerts,
        hot_lead_keywords: aiSettings.hotLeadKeywords,
        
        // Email filtering settings
        auto_archive_spam: automationSettings.emailFiltering.autoArchiveSpam,
        block_mass_emails: automationSettings.emailFiltering.blockMassEmails,
        personal_only: automationSettings.emailFiltering.personalOnly,
        skip_auto_generated: automationSettings.emailFiltering.skipAutoGenerated,
        
        // Business rules - THESE ARE THE KEY ONES!
        blacklist_emails: automationSettings.businessRules.blacklist,
        whitelist_emails: automationSettings.businessRules.whitelist,
        priority_keywords: automationSettings.businessRules.customKeywords
      };

      console.log('ðŸ’¾ Saving all settings with business rules:', settingsToSave);

      // ðŸŽ¯ CRITICAL: Use the new endpoint that properly handles JSONB
      const response = await fetch('/api/email-settings/save', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(settingsToSave)
      });

      if (response.ok) {
        const result = await response.json();
        console.log('âœ… Settings saved successfully:', result);
        
        // Show what was actually saved
        if (result.processed) {
          console.log('ðŸ“‹ Saved business rules:', {
            blacklist: result.processed.blacklist_emails,
            whitelist: result.processed.whitelist_emails,
            priority: result.processed.priority_keywords
          });
        }
        
        alert('âœ… Settings saved successfully!');
      } else {
        const errorData = await response.json();
        console.error('âŒ Failed to save settings:', errorData);
        alert(`âŒ Failed to save settings: ${errorData.error || 'Unknown error'}`);
      }
    } catch (error) {
      console.error('âŒ Error saving settings:', error);
      alert('âŒ Error saving settings. Please try again.');
    } finally {
      setSaving(false);
    }
  };

  const testAIResponse = async () => {
    setTesting(true);
    setTestResult(null);
    try {
      const response = await fetch('/api/customer/test-ai-response', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          message: "Hi, I'm urgently looking for a 3-bedroom house under $500K. Can you help me find something ASAP? I'm ready to buy immediately.",
          settings: {
            ...aiSettings,
            business_name: businessProfileRef.current.name,
            knowledge_base: knowledgeBaseRef.current,
            custom_instructions: aiSettings.customInstructions,
            ai_model: aiSettings.aiModel,
            ai_temperature: aiSettings.creativity,
            response_length: aiSettings.responseLength,
            enable_ai_responses: autoPollStatus.isEnabled // Use unified state
          }
        })
      });

      const data = await response.json();
      if (data.success) {
        setTestResult(data);
      } else {
        alert('Error testing AI: ' + data.error);
      }
    } catch (error) {
      console.error('Error testing AI:', error);
      alert('Error testing AI response');
    } finally {
      setTesting(false);
    }
  };

  const connectGmail = () => {
    if (gmailConnection) {
      setReconnecting(true);
      console.log('ðŸ”— Reconnecting Gmail account...');
    } else {
      console.log('ðŸ”— Connecting Gmail account...');
    }
    window.location.href = '/api/auth/google';
  };

  const checkGmailEmails = async (silent = false) => {
    if (!gmailConnection) {
      console.log('No Gmail connection available');
      return;
    }
    
    if (!silent) setGmailLoading(true);
    try {
      const response = await fetch('/api/gmail/monitor', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action: 'check',
          emailAddress: gmailConnection.email
        })
      });

      if (response.ok) {
        const data = await response.json();
        setGmailEmails(data.emails || []);
        
        if (!silent) setLastRefresh(new Date());
        
        // ðŸŽ¯ NEW: Show blacklist status if any were filtered
        if (data.blacklistedCount > 0) {
          console.log(`ðŸš« ${data.blacklistedCount} blacklisted emails were archived`);
        }
      } else if (response.status === 401) {
        console.log('âš ï¸ Gmail token refresh failed - needs reconnection');
        setNeedsReconnect(true);
      } else if (response.status === 404) {
        console.log('âš ï¸ Gmail monitor API not available');
      } else {
        console.error('Gmail check failed:', response.status);
      }
    } catch (error) {
      console.error('Error checking Gmail emails:', error);
    } finally {
      if (!silent) setGmailLoading(false);
    }
  };

  const fetchOutlookEmails = async () => {
    try {
      const res = await fetch('/api/outlook/inbox');
      if (res.ok) {
        const data = await res.json();
        setOutlookEmails(data.emails || []);
      }
    } catch {}
  };

  const sendAIResponse = async (emailId, preview = false) => {
    if (!gmailConnection) return;
    
    setResponding(true);
    try {
      console.log('ðŸš€ Sending AI response:', { emailId, preview, selectedEmail: selectedGmailEmail });
      
      const response = await fetch('/api/gmail/monitor', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action: 'respond',
          emailAddress: gmailConnection.email,
          emailId: emailId,
          actualSend: !preview
        })
      });

      if (response.ok) {
        const data = await response.json();
        console.log('ðŸ“§ API Response:', data);
        
        // ðŸŽ¯ NEW: Check if email was blacklisted
        if (data.filtered && data.isBlacklisted) {
          alert(`ðŸš« This email is blacklisted. No response will be sent.`);
          return data;
        }
        
        if (!preview && data.success) {
          const sentEmail = {
            id: `sent-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
            originalEmailId: emailId,
            to: selectedGmailEmail?.fromEmail || 'unknown@example.com',
            toName: selectedGmailEmail?.fromName || selectedGmailEmail?.fromEmail || 'Unknown Contact',
            originalSubject: selectedGmailEmail?.subject || 'No Subject',
            response: data.response || data.aiResponse || 'Response sent successfully',
            sentTime: new Date().toLocaleString(),
            timestamp: new Date(),
            status: 'sent'
          };
          
          console.log('ðŸ“¤ Adding sent email to state:', sentEmail);
          setSentEmails(prev => {
            const updated = [sentEmail, ...prev];
            console.log('ðŸ“‹ Updated sent emails:', updated);
            return updated;
          });
          
          // Update stats
          setStats(prev => ({
            ...prev,
            totalResponsesSent: prev.totalResponsesSent + 1
          }));
          
          setTimeout(() => {
            setActiveEmailView('sent');
            console.log('ðŸ”„ Switched to sent tab');
          }, 500);
        }
        
        if (!preview) {
          setTimeout(() => checkGmailEmails(false), 1000);
        }
        return data;
      } else {
        console.error('âŒ API response not ok:', response.status, response.statusText);
      }
    } catch (error) {
      console.error('âŒ Error sending AI response:', error);
    } finally {
      setResponding(false);
    }
  };

  const addToBlacklist = useCallback(() => {
    if (newBlacklistItem.trim()) {
      setAutomationSettings(prev => ({
        ...prev,
        businessRules: {
          ...prev.businessRules,
          blacklist: [...prev.businessRules.blacklist, newBlacklistItem.trim()]
        }
      }));
      setNewBlacklistItem('');
    }
  }, [newBlacklistItem]);

  const removeFromBlacklist = useCallback((index) => {
    setAutomationSettings(prev => ({
      ...prev,
      businessRules: {
        ...prev.businessRules,
        blacklist: prev.businessRules.blacklist.filter((_, i) => i !== index)
      }
    }));
  }, []);

  const addToWhitelist = useCallback(() => {
    if (newWhitelistItem.trim()) {
      setAutomationSettings(prev => ({
        ...prev,
        businessRules: {
          ...prev.businessRules,
          whitelist: [...prev.businessRules.whitelist, newWhitelistItem.trim()]
        }
      }));
      setNewWhitelistItem('');
    }
  }, [newWhitelistItem]);

  const removeFromWhitelist = useCallback((index) => {
    setAutomationSettings(prev => ({
      ...prev,
      businessRules: {
        ...prev.businessRules,
        whitelist: prev.businessRules.whitelist.filter((_, i) => i !== index)
      }
    }));
  }, []);

  const addCustomKeyword = useCallback(() => {
    if (newCustomKeyword.trim()) {
      setAutomationSettings(prev => ({
        ...prev,
        businessRules: {
          ...prev.businessRules,
          customKeywords: [...prev.businessRules.customKeywords, newCustomKeyword.trim()]
        }
      }));
      setNewCustomKeyword('');
    }
  }, [newCustomKeyword]);

  const removeCustomKeyword = useCallback((index) => {
    setAutomationSettings(prev => ({
      ...prev,
      businessRules: {
        ...prev.businessRules,
        customKeywords: prev.businessRules.customKeywords.filter((_, i) => i !== index)
      }
    }));
  }, []);

  const addHotLeadKeyword = useCallback(() => {
    const input = document.getElementById('hotLeadKeywordInput');
    if (input && input.value.trim()) {
      const newKeyword = input.value.trim();
      if (!aiSettings.hotLeadKeywords.includes(newKeyword)) {
        setAiSettings(prev => ({
          ...prev,
          hotLeadKeywords: [...prev.hotLeadKeywords, newKeyword]
        }));
      }
      input.value = '';
    }
  }, [aiSettings.hotLeadKeywords]);

  const removeHotLeadKeyword = useCallback((index) => {
    setAiSettings(prev => ({
      ...prev,
      hotLeadKeywords: prev.hotLeadKeywords.filter((_, i) => i !== index)
    }));
  }, []);

  // UPDATED DashboardTab Component with cleaner UI
  const DashboardTab = () => (
    <div className="space-y-6">

      {/* Reconnect banner â€” shown when token refresh fails */}
      {needsReconnect && (
        <div className="bg-amber-500/10 border border-amber-500/30 rounded-xl p-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <AlertCircle className="w-5 h-5 text-amber-400 flex-shrink-0" />
            <div>
              <p className="text-amber-300 font-medium text-sm">Gmail token expired â€” reconnection required</p>
              <p className="text-amber-400/70 text-xs mt-0.5">Go to the Connections tab and click "Connect Gmail" to restore access.</p>
            </div>
          </div>
          <button
            onClick={() => { setNeedsReconnect(false); setActiveTab('connections'); }}
            className="px-4 py-1.5 bg-amber-500 hover:bg-amber-600 text-white text-xs font-semibold rounded-lg transition-colors flex-shrink-0 ml-4"
          >
            Go to Connections
          </button>
        </div>
      )}

      {/* CONSOLIDATED: Professional Gmail AI Control Panel */}
      {gmailConnection ? (
        <div className="bg-[#161B22] rounded-xl border border-gray-800 p-6">
          <div className="flex items-center justify-between">
            {/* Left Section: Status & Connection Info */}
            <div className="flex items-center gap-4">
              <div className="flex items-center gap-3">
                <CheckCircle className="w-5 h-5 text-green-400" />
                <div>
                  <h3 className="font-medium text-white flex items-center gap-2">
                    AI Auto-Responses
                    {autoPollStatus.isRunning ? (
                      <span className="px-2 py-0.5 rounded-md bg-green-500/20 text-green-400 text-xs font-medium">
                        ACTIVE
                      </span>
                    ) : (
                      <span className="px-2 py-0.5 rounded-md bg-gray-500/20 text-gray-400 text-xs font-medium">
                        STOPPED
                      </span>
                    )}
                  </h3>
                  <p className="text-xs text-gray-400 mt-0.5">
                    {gmailConnection.email} &middot; Auto-monitoring active
                  </p>
                </div>
              </div>
            </div>
            
            {/* Right Section: Action Buttons */}
            <div className="flex items-center gap-2">
              <span className="text-xs text-gray-500 mr-2">
                Last refreshed: {lastRefresh.toLocaleTimeString()}
              </span>
              <Button 
                onClick={() => checkGmailEmails(false)}
                disabled={gmailLoading}
                size="sm"
                variant="outline"
                className="bg-[#161B22] border-gray-800 text-gray-400 hover:text-white hover:bg-white/5 text-xs px-3 py-1.5"
              >
                {gmailLoading ? (
                  <>
                    <RefreshCw className="w-3 h-3 animate-spin mr-1" />
                    Checking...
                  </>
                ) : (
                  <>
                    <RefreshCw className="w-3 h-3 mr-1" />
                    Refresh
                  </>
                )}
              </Button>
              <Button 
                onClick={toggleAutoPoll}
                disabled={saving || !gmailConnection}
                size="sm"
                className={`px-4 py-1.5 text-xs font-medium transition-all ${
                  autoPollStatus.isRunning
                    ? 'bg-red-600 hover:bg-red-700 text-white'
                    : 'bg-green-600 hover:bg-green-700 text-white'
                }`}
              >
                {saving ? (
                  'Saving...'
                ) : autoPollStatus.isRunning ? (
                  'Stop Auto-Responses'
                ) : (
                  'Start Auto-Responses'
                )}
              </Button>
            </div>
          </div>
          
          {/* Bottom Stats Bar - Only show when there's activity */}
          {(autoPollStatus.lastPoll || autoPollStatus.totalEmailsProcessed > 0) && (
            <div className="mt-4 pt-3 border-t border-white/5 flex items-center justify-between text-xs">
              <div className="flex items-center gap-4 text-gray-400">
                {autoPollStatus.lastPoll && (
                  <span>
                    Last checked: {autoPollStatus.lastPoll.toLocaleTimeString()}
                  </span>
                )}
              </div>
              <div className="flex gap-4">
                <span className="text-gray-400">
                  <span className="font-medium text-white">{autoPollStatus.totalEmailsProcessed}</span> Emails Checked
                </span>
                <span className="text-gray-400">
                  <span className="font-medium text-white">{autoPollStatus.totalResponsesSent}</span> AI Responses Sent
                </span>
              </div>
            </div>
          )}
        </div>
      ) : (
        <div className="bg-yellow-500/5 rounded-xl border border-yellow-500/20 p-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <AlertCircle className="w-5 h-5 text-yellow-400" />
              <div>
                <h3 className="font-medium text-white">Gmail AI Setup Required</h3>
                <p className="text-sm text-gray-400 mt-0.5">
                  Connect Gmail for AI-powered email automation
                </p>
              </div>
            </div>
            <Button 
              onClick={connectGmail} 
              className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 text-sm"
            >
              <LinkIcon className="w-3.5 h-3.5 mr-1.5" />
              Connect Gmail
            </Button>
          </div>
        </div>
      )}

      {/* UPDATED: New 4-Metric Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {/* AI Responses Sent */}
        <div className="bg-[#161B22] rounded-xl border border-gray-800 p-5">
          <div className="flex items-start justify-between">
            <div>
              <p className="text-xs font-medium text-gray-400 uppercase tracking-wider">AI Responses</p>
              <p className="text-2xl font-bold text-white mt-1">{stats.totalResponsesSent || autoPollStatus.totalResponsesSent}</p>
              <p className="text-xs text-gray-500 mt-1">Total sent</p>
            </div>
            <div className="p-2 rounded-lg bg-green-500/10">
              <Send className="w-5 h-5 text-green-400" />
            </div>
          </div>
        </div>

        {/* Leads Captured */}
        <div className="bg-[#161B22] rounded-xl border border-gray-800 p-5">
          <div className="flex items-start justify-between">
            <div>
              <p className="text-xs font-medium text-gray-400 uppercase tracking-wider">Leads Captured</p>
              <p className="text-2xl font-bold text-white mt-1">{stats.totalLeadsCaptured}</p>
              <p className="text-xs text-gray-500 mt-1">With contact info</p>
            </div>
            <div className="p-2 rounded-lg bg-blue-500/10">
              <UserCheck className="w-5 h-5 text-blue-400" />
            </div>
          </div>
        </div>

        {/* Meetings Booked */}
        <div className="bg-[#161B22] rounded-xl border border-gray-800 p-5">
          <div className="flex items-start justify-between">
            <div>
              <p className="text-xs font-medium text-gray-400 uppercase tracking-wider">Meetings Booked</p>
              <p className="text-2xl font-bold text-white mt-1">{stats.meetingsBooked}</p>
              <p className="text-xs text-gray-500 mt-1">This month</p>
            </div>
            <div className="p-2 rounded-lg bg-purple-500/10">
              <Calendar className="w-5 h-5 text-purple-400" />
            </div>
          </div>
        </div>

        {/* Response Time */}
        <div className="bg-[#161B22] rounded-xl border border-gray-800 p-5">
          <div className="flex items-start justify-between">
            <div>
              <p className="text-xs font-medium text-gray-400 uppercase tracking-wider">Response Time</p>
              <p className="text-2xl font-bold text-white mt-1">{formatTime(stats.avgResponseTimeMinutes)}</p>
              <p className="text-xs text-gray-500 mt-1">Average speed</p>
            </div>
            <div className="p-2 rounded-lg bg-orange-500/10">
              <Clock className="w-5 h-5 text-orange-400" />
            </div>
          </div>
        </div>
      </div>

      {/* Email Lists - Keep all existing email list code */}
      <div className="grid grid-cols-1 lg:grid-cols-5 gap-6">
        {/* Keep all the existing email list JSX here - not changed */}
        <div className="lg:col-span-2">
          <div className="bg-[#161B22] rounded-xl border border-gray-800 h-[calc(100vh-480px)] min-h-[600px] flex flex-col">
            {/* All existing inbox/sent tabs code */}
            <div className="p-6 pb-0 flex-shrink-0 border-b border-white/10">
              <div className="flex items-center gap-3 mb-4">
                <Inbox className="w-6 h-6 text-blue-400" />
                <h3 className="text-xl font-semibold text-white">Email Conversations</h3>
                <div className="ml-auto px-3 py-1 rounded-full bg-blue-500/20 text-blue-300 text-sm font-medium">
                  {gmailEmails.length + outlookEmails.length + sentEmails.length} Total
                </div>
              </div>
              
              <div className="w-full mb-4">
                <div className="grid grid-cols-2 gap-0 bg-white/5 rounded-xl p-1 border border-white/10">
                  <button
                    onClick={() => setActiveEmailView('inbox')}
                    className={`relative px-4 py-3 rounded-lg font-medium text-sm transition-all duration-300 ${
                      activeEmailView === 'inbox' 
                        ? 'bg-blue-600 text-white shadow-xl transform scale-[0.98]' 
                        : 'text-gray-300 hover:text-white hover:bg-white/5'
                    }`}
                  >
                    <div className="flex items-center justify-center gap-2">
                      <Inbox className="w-4 h-4" />
                      <span>Inbox</span>
                      <div className={`px-2 py-1 rounded-full text-xs font-bold ${
                        activeEmailView === 'inbox' 
                          ? 'bg-white/5 text-white' 
                          : 'bg-blue-500/20 text-blue-300'
                      }`}>
                        {gmailEmails.length + outlookEmails.length}
                      </div>
                    </div>
                    {activeEmailView === 'inbox' && (
                      <div className="absolute bottom-0 left-1/2 transform -translate-x-1/2 w-8 h-0.5 bg-white rounded-full"></div>
                    )}
                  </button>
                  
                  <button
                    onClick={() => setActiveEmailView('sent')}
                    className={`relative px-4 py-3 rounded-lg font-medium text-sm transition-all duration-300 ${
                      activeEmailView === 'sent' 
                        ? 'bg-green-600 text-white shadow-xl transform scale-[0.98]' 
                        : 'text-gray-300 hover:text-white hover:bg-white/5'
                    }`}
                  >
                    <div className="flex items-center justify-center gap-2">
                      <Send className="w-4 h-4" />
                      <span>Sent</span>
                      <div className={`px-2 py-1 rounded-full text-xs font-bold ${
                        activeEmailView === 'sent' 
                          ? 'bg-white/5 text-white' 
                          : 'bg-green-500/20 text-green-300'
                      }`}>
                        {sentEmails.length}
                      </div>
                    </div>
                    {activeEmailView === 'sent' && (
                      <div className="absolute bottom-0 left-1/2 transform -translate-x-1/2 w-8 h-0.5 bg-white rounded-full"></div>
                    )}
                  </button>
                </div>
                
                <div className="flex items-center justify-between mt-3 text-sm text-gray-400">
                  <span>
                    {activeEmailView === 'inbox'
                      ? 'Real-time Gmail + Outlook monitoring with AI responses'
                      : 'AI responses sent to customers'
                    }
                  </span>
                  <div className="flex gap-2">
                    <button
                      onClick={() => {
                        const testEmail = {
                          id: `test-${Date.now()}`,
                          to: 'test@example.com',
                          toName: 'Test Customer',
                          originalSubject: 'Test Inquiry',
                          response: 'This is a test AI response to demonstrate the sent email functionality.',
                          sentTime: new Date().toLocaleString(),
                          timestamp: new Date(),
                          status: 'sent'
                        };
                        setSentEmails(prev => [testEmail, ...prev]);
                        setActiveEmailView('sent');
                      }}
                      className="px-2 py-1 rounded-md bg-yellow-600/20 text-yellow-400 text-xs hover:bg-yellow-600/30 transition-colors"
                    >
                      + Add Test
                    </button>
                  </div>
                </div>
              </div>
            </div>

            <div className="flex-1 flex flex-col overflow-hidden">
              {activeEmailView === 'inbox' && (
                <div className="flex-1 flex flex-col h-full">
                  <div className="flex-1 overflow-y-auto custom-scrollbar">
                    <style jsx>{`
                      .custom-scrollbar {
                        scrollbar-width: auto;
                        scrollbar-color: rgba(59, 130, 246, 0.6) rgba(255, 255, 255, 0.1);
                      }
                      .custom-scrollbar::-webkit-scrollbar {
                        width: 14px;
                      }
                      .custom-scrollbar::-webkit-scrollbar-track {
                        background: rgba(255, 255, 255, 0.05);
                        border-radius: 10px;
                        margin: 6px;
                        border: 1px solid rgba(255, 255, 255, 0.1);
                      }
                      .custom-scrollbar::-webkit-scrollbar-thumb {
                        background: linear-gradient(180deg, rgba(59, 130, 246, 0.8), rgba(37, 99, 235, 0.8));
                        border-radius: 10px;
                        border: 2px solid rgba(255, 255, 255, 0.1);
                        box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.2);
                      }
                      .custom-scrollbar::-webkit-scrollbar-thumb:hover {
                        background: linear-gradient(180deg, rgba(59, 130, 246, 1), rgba(37, 99, 235, 1));
                        box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.3);
                      }
                      .custom-scrollbar::-webkit-scrollbar-thumb:active {
                        background: linear-gradient(180deg, rgba(37, 99, 235, 1), rgba(29, 78, 216, 1));
                      }
                      .custom-scrollbar::-webkit-scrollbar-corner {
                        background: transparent;
                      }
                    `}</style>
                    
                    {(gmailEmails.length === 0 && outlookEmails.length === 0) ? (
                      <div className="p-8 text-center h-full flex flex-col items-center justify-center">
                        <div className="w-16 h-16 bg-blue-500/20 rounded-full flex items-center justify-center mb-4">
                          <Mail className="w-8 h-8 text-blue-400" />
                        </div>
                        <h4 className="text-lg font-medium text-white mb-2">No emails yet</h4>
                        <p className="text-gray-400 text-center max-w-sm">
                          {gmailConnection 
                            ? 'New emails will appear here automatically when received'
                            : 'Connect Gmail to start monitoring your emails'
                          }
                        </p>
                        {gmailConnection && (
                          <Button 
                            onClick={() => checkGmailEmails(false)}
                            disabled={gmailLoading}
                            className="mt-4 bg-blue-600 hover:bg-blue-700 text-white"
                          >
                            {gmailLoading ? (
                              <RefreshCw className="w-4 h-4 animate-spin mr-2" />
                            ) : (
                              <RefreshCw className="w-4 h-4 mr-2" />
                            )}
                            Check for emails
                          </Button>
                        )}
                      </div>
                    ) : (
                      <div className="space-y-0">
                        {[
                          ...gmailEmails.map(e => ({ ...e, source: 'gmail' })),
                          ...outlookEmails,
                        ]
                          .sort((a, b) => new Date(b.receivedAt || 0) - new Date(a.receivedAt || 0))
                          .map((email, index) => {
                            const isGmail = email.source === 'gmail';
                            const isSelected = isGmail
                              ? selectedGmailEmail?.id === email.id
                              : selectedOutlookEmail?.id === email.id;
                            return (
                              <div
                                key={email.id}
                                className={`p-4 border-b border-white/5 cursor-pointer transition-all duration-200 hover:bg-white/5 ${
                                  isSelected ? 'bg-blue-500/20 border-l-4 border-l-blue-400 shadow-lg' : ''
                                } ${index === 0 ? 'border-t-0' : ''}`}
                                onClick={() => {
                                  if (isGmail) {
                                    setSelectedGmailEmail(email);
                                    setSelectedOutlookEmail(null);
                                    setShowingPreview(false);
                                    setPreviewResponse(null);
                                  } else {
                                    setSelectedOutlookEmail(email);
                                    setSelectedGmailEmail(null);
                                    setShowingPreview(false);
                                  }
                                  setSelectedConversation(null);
                                }}
                              >
                                <div className="flex items-center justify-between mb-2">
                                  <h4 className="font-semibold text-sm text-white truncate flex-1 mr-2">
                                    {email.fromName || email.fromEmail}
                                  </h4>
                                  <div className="flex items-center gap-2">
                                    {isGmail ? (
                                      <div className="px-2 py-1 rounded-full bg-red-500/20 text-red-300 text-xs font-medium flex items-center gap-1">
                                        <svg className="w-3 h-3" viewBox="0 0 24 24"><path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" fill="#4285F4"/><path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853"/><path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" fill="#FBBC05"/><path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335"/></svg>
                                        Gmail
                                      </div>
                                    ) : (
                                      <div className="px-2 py-1 rounded-full bg-blue-500/20 text-blue-300 text-xs font-medium flex items-center gap-1">
                                        <svg className="w-3 h-3" viewBox="0 0 24 24" fill="none"><rect width="24" height="24" rx="3" fill="#0078D4"/><path d="M13 6h7v12h-7V6z" fill="#50D9FF" opacity=".8"/><path d="M4 8.5C4 7.12 5.12 6 6.5 6S9 7.12 9 8.5v7C9 16.88 7.88 18 6.5 18S4 16.88 4 15.5v-7z" fill="white"/><ellipse cx="6.5" cy="12" rx="2.5" ry="3.5" fill="#0078D4"/></svg>
                                        Outlook
                                      </div>
                                    )}
                                    {isSelected && <div className="w-2 h-2 rounded-full bg-blue-400" />}
                                  </div>
                                </div>
                                <p className="text-xs text-gray-300 font-medium mb-1 truncate">{email.subject}</p>
                                <p className="text-xs text-gray-400 line-clamp-2 mb-2 leading-relaxed">
                                  {email.snippet || email.body}
                                </p>
                                <div className="flex items-center justify-between">
                                  <p className="text-xs text-gray-500">{email.receivedTime}</p>
                                  <div className="text-xs text-gray-500">from {email.fromEmail?.split('@')[1] || 'unknown'}</div>
                                </div>
                              </div>
                            );
                          })}
                      </div>
                    )}
                  </div>
                </div>
              )}

              {activeEmailView === 'sent' && (
                <div className="flex-1 flex flex-col h-full">
                  <div className="flex-1 overflow-y-auto custom-scrollbar-green">
                    <style jsx>{`
                      .custom-scrollbar-green {
                        scrollbar-width: auto;
                        scrollbar-color: rgba(34, 197, 94, 0.6) rgba(255, 255, 255, 0.1);
                      }
                      .custom-scrollbar-green::-webkit-scrollbar {
                        width: 14px;
                      }
                      .custom-scrollbar-green::-webkit-scrollbar-track {
                        background: rgba(255, 255, 255, 0.05);
                        border-radius: 10px;
                        margin: 6px;
                        border: 1px solid rgba(255, 255, 255, 0.1);
                      }
                      .custom-scrollbar-green::-webkit-scrollbar-thumb {
                        background: linear-gradient(180deg, rgba(34, 197, 94, 0.8), rgba(21, 128, 61, 0.8));
                        border-radius: 10px;
                        border: 2px solid rgba(255, 255, 255, 0.1);
                        box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.2);
                      }
                      .custom-scrollbar-green::-webkit-scrollbar-thumb:hover {
                        background: linear-gradient(180deg, rgba(34, 197, 94, 1), rgba(21, 128, 61, 1));
                        box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.3);
                      }
                      .custom-scrollbar-green::-webkit-scrollbar-thumb:active {
                        background: linear-gradient(180deg, rgba(21, 128, 61, 1), rgba(20, 83, 45, 1));
                      }
                    `}</style>
                    
                    {sentEmails.length === 0 ? (
                      <div className="p-8 text-center h-full flex flex-col items-center justify-center">
                        <div className="w-16 h-16 bg-green-500/20 rounded-full flex items-center justify-center mb-4">
                          <Send className="w-8 h-8 text-green-400" />
                        </div>
                        <h4 className="text-lg font-medium text-white mb-2">No responses sent yet</h4>
                        <p className="text-gray-400 text-center max-w-sm leading-relaxed">
                          AI responses will appear here after you send them to customers. 
                          Select an email from the inbox and use the AI response feature.
                        </p>
                        <div className="mt-6 p-4 bg-green-500/10 border border-green-500/20 rounded-lg max-w-sm">
                          <p className="text-green-300 text-sm">
                            <strong>Tip:</strong> Use the "+ Add Test" button above to see how sent emails will look
                          </p>
                        </div>
                      </div>
                    ) : (
                      <div className="space-y-0">
                        {sentEmails.map((sentEmail, index) => (
                          <div
                            key={sentEmail.id}
                            className={`p-4 border-b border-white/5 cursor-pointer hover:bg-white/5 transition-all duration-200 ${
                              selectedConversation?.id === sentEmail.id 
                                ? 'bg-green-500/20 border-l-4 border-l-green-400 shadow-lg' 
                                : ''
                            } ${index === 0 ? 'border-t-0' : ''}`}
                            onClick={() => {
                              console.log('ðŸ“§ Clicked sent email:', sentEmail);
                              setSelectedGmailEmail(null);
                              setSelectedConversation(sentEmail);
                            }}
                          >
                            <div className="flex items-center justify-between mb-2">
                              <h4 className="font-semibold text-sm text-white truncate flex-1 mr-2">
                                To: {sentEmail.toName || sentEmail.to}
                              </h4>
                              <div className="flex items-center gap-2">
                                <div className="px-2 py-1 rounded-full bg-green-500/20 text-green-300 text-xs font-medium">
                                  âœ“ Sent
                                </div>
                                {selectedConversation?.id === sentEmail.id && (
                                  <div className="w-2 h-2 rounded-full bg-green-400"></div>
                                )}
                              </div>
                            </div>
                            <p className="text-xs text-gray-300 mb-1 truncate">
                              Re: {sentEmail.originalSubject}
                            </p>
                            <p className="text-xs text-gray-400 line-clamp-2 mb-2 leading-relaxed">
                              {sentEmail.response?.substring(0, 100)}...
                            </p>
                            <div className="flex items-center justify-between">
                              <p className="text-xs text-gray-500">
                                {sentEmail.sentTime}
                              </p>
                              <div className="text-xs text-gray-500">
                                to {sentEmail.to.split('@')[1] || 'unknown'}
                              </div>
                            </div>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Email Details Panel - Keep all existing code */}
        <div className="lg:col-span-3 space-y-6">
          {selectedOutlookEmail ? (
            <div className="bg-[#161B22] rounded-xl border border-gray-800 h-[calc(100vh-480px)] min-h-[600px] flex flex-col">
              <div className="p-6 pb-4 border-b border-white/10 flex-shrink-0">
                <div className="flex items-center gap-3 text-lg font-semibold text-white mb-2">
                  <Mail className="w-5 h-5 text-blue-400" />
                  <div className="flex-1 min-w-0">
                    <div className="text-white truncate">{selectedOutlookEmail.fromName || selectedOutlookEmail.fromEmail}</div>
                  </div>
                  <Badge className="bg-blue-500/20 text-blue-300 border-blue-500/30 flex items-center gap-1">
                    <svg className="w-3 h-3" viewBox="0 0 24 24" fill="none"><rect width="24" height="24" rx="3" fill="#0078D4"/><path d="M13 6h7v12h-7V6z" fill="#50D9FF" opacity=".8"/><path d="M4 8.5C4 7.12 5.12 6 6.5 6S9 7.12 9 8.5v7C9 16.88 7.88 18 6.5 18S4 16.88 4 15.5v-7z" fill="white"/><ellipse cx="6.5" cy="12" rx="2.5" ry="3.5" fill="#0078D4"/></svg>
                    Outlook Inbox
                  </Badge>
                </div>
                <p className="text-sm text-gray-300">
                  <span className="font-medium">Subject:</span> {selectedOutlookEmail.subject}
                </p>
                <p className="text-xs text-gray-500 mt-1">From: {selectedOutlookEmail.fromEmail}</p>
              </div>
              <div className="flex-1 p-6 space-y-6 overflow-y-auto">
                <div className="bg-[#161B22] rounded-xl p-6 border border-gray-800">
                  <p className="text-sm font-medium text-gray-300 mb-4 flex items-center gap-2">
                    <Mail className="w-4 h-4" />
                    Email Content:
                  </p>
                  <div className="max-h-64 overflow-y-auto text-sm text-gray-300 leading-relaxed whitespace-pre-wrap">
                    {selectedOutlookEmail.fullBody || 'No content available'}
                  </div>
                </div>
                {selectedOutlookEmail.aiReply && (
                  <div className="bg-green-500/10 rounded-xl p-6 border border-green-500/20">
                    <p className="text-sm font-medium text-green-300 mb-4 flex items-center gap-2">
                      <Bot className="w-4 h-4" />
                      AI Reply Sent:
                    </p>
                    <div className="text-sm text-gray-300 leading-relaxed whitespace-pre-wrap">
                      {selectedOutlookEmail.aiReply}
                    </div>
                  </div>
                )}
              </div>
            </div>
          ) : selectedGmailEmail ? (
            <div className="bg-[#161B22] rounded-xl border border-gray-800 h-[calc(100vh-480px)] min-h-[600px] flex flex-col">
              <div className="p-6 pb-4 border-b border-white/10 flex-shrink-0">
                <div className="flex items-center gap-3 text-lg font-semibold text-white mb-2">
                  <Globe className="w-5 h-5 text-blue-400" />
                  <div className="flex-1 min-w-0">
                    <div className="text-white truncate">
                      {selectedGmailEmail.fromName || selectedGmailEmail.fromEmail}
                    </div>
                  </div>
                  <Badge className="bg-blue-500/20 text-blue-300 border-blue-500/30">
                    Gmail Inbox
                  </Badge>
                </div>
                <p className="text-sm text-gray-300">
                  <span className="font-medium">Subject:</span> {selectedGmailEmail.subject}
                </p>
              </div>
              
              <div className="flex-1 p-6 space-y-6 overflow-y-auto">
                <div className="bg-[#161B22] rounded-xl p-6 border border-gray-800">
                  <p className="text-sm font-medium text-gray-300 mb-4 flex items-center gap-2">
                    <Mail className="w-4 h-4" />
                    Email Content:
                  </p>
                  <div className="max-h-64 overflow-y-auto text-sm text-gray-300 leading-relaxed space-y-2 custom-scrollbar">
                    {selectedGmailEmail.fullBody || selectedGmailEmail.body || 'No content preview available'}
                  </div>
                </div>

                {/* ðŸŽ¯ ADDED: Preview section - Always rendered but conditionally visible */}
                <div 
                  className={`bg-purple-500/10 rounded-xl p-6 border border-purple-500/20  ${
                    showingPreview && previewResponse ? 'block' : 'hidden'
                  }`}
                >
                  <p className="text-sm font-medium text-purple-300 mb-4 flex items-center gap-2">
                    <Eye className="w-4 h-4" />
                    AI Response Preview (Editable):
                  </p>
                  <textarea
                    ref={previewTextareaRef}
                    value={editedResponse}
                    onChange={(e) => setEditedResponse(e.target.value)}
                    className="w-full h-48 px-3 py-2 bg-[#0D1117] border border-gray-800 rounded-md text-white placeholder:text-gray-600 focus:border-violet-500 focus:outline-none resize-none"
                    placeholder="AI response will appear here..."
                  />
                  <div className="mt-4 flex gap-2">
                    <Button
                      onClick={() => setEditedResponse(previewResponse || '')}
                      size="sm"
                      variant="outline"
                      className="bg-[#161B22] border-gray-800 text-gray-300 hover:text-white hover:bg-white/5"
                    >
                      Reset to Original
                    </Button>
                    <Button
                      onClick={sendEditedResponse}
                      disabled={responding}
                      size="sm"
                      className="bg-purple-600 hover:bg-purple-700 text-white"
                    >
                      {responding ? (
                        <>
                          <RefreshCw className="w-4 h-4 animate-spin mr-1" />
                          Sending...
                        </>
                      ) : (
                        <>
                          <Send className="w-4 h-4 mr-1" />
                          Send Edited Response
                        </>
                      )}
                    </Button>
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <Button 
                    onClick={() => handlePreviewAIResponse(selectedGmailEmail.id)}
                    disabled={generatingPreview || !autoPollStatus.isEnabled}
                    variant="outline"
                    className="h-14 flex items-center justify-center gap-3 text-base bg-[#161B22] border-gray-800 text-gray-300 hover:text-white hover:bg-white/5  disabled:opacity-50"
                  >
                    {generatingPreview ? (
                      <>
                        <RefreshCw className="w-5 h-5 animate-spin" />
                        Generating Preview...
                      </>
                    ) : (
                      <>
                        <Eye className="w-5 h-5" />
                        Preview AI Response
                      </>
                    )}
                  </Button>
                  <Button 
                    onClick={() => sendAIResponse(selectedGmailEmail.id, false)}
                    disabled={responding || !autoPollStatus.isEnabled}
                    className="h-14 flex items-center justify-center gap-3 text-base bg-blue-600 hover:bg-blue-700 text-white disabled:opacity-50"
                  >
                    {responding ? (
                      <>
                        <RefreshCw className="w-5 h-5 animate-spin" />
                        Sending Response...
                      </>
                    ) : (
                      <>
                        <Send className="w-5 h-5" />
                        Send AI Response
                      </>
                    )}
                  </Button>
                </div>

                {!autoPollStatus.isEnabled && (
                  <div className="bg-yellow-500/20 border border-yellow-500/30 rounded-xl p-4">
                    <div className="flex items-center gap-2">
                      <AlertCircle className="w-5 h-5 text-yellow-400" />
                      <p className="text-yellow-300 text-sm">
                        AI responses are currently disabled. Click "Start Auto-Responses" to enable.
                      </p>
                    </div>
                  </div>
                )}

                <div className="bg-blue-500/10 border border-blue-500/20 rounded-xl p-6">
                  <div className="flex items-start gap-4">
                    <div className="w-10 h-10 bg-blue-500/30 rounded-full flex items-center justify-center flex-shrink-0">
                      <Bot className="w-5 h-5 text-blue-300" />
                    </div>
                    <div className="flex-1">
                      <p className="text-base font-medium text-blue-200 mb-2">AI Response Ready</p>
                      <p className="text-sm text-blue-300 leading-relaxed">
                        The AI will generate a professional response based on your business knowledge and custom instructions. 
                        You can preview the response before sending to ensure it meets your standards.
                      </p>
                    </div>
                  </div>
                </div>

                <div className="bg-[#161B22] rounded-xl p-4 space-y-3 border border-gray-800">
                  <h4 className="font-medium text-white">Email Details</h4>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
                    <div>
                      <span className="font-medium text-gray-400">From:</span>
                      <p className="text-gray-300">{selectedGmailEmail.fromEmail}</p>
                    </div>
                    <div>
                      <span className="font-medium text-gray-400">Received:</span>
                      <p className="text-gray-300">{selectedGmailEmail.receivedTime}</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          ) : selectedConversation ? (
            <div className="bg-[#161B22] rounded-xl border border-gray-800 h-[calc(100vh-480px)] min-h-[600px] flex flex-col">
              <div className="p-6 pb-4 border-b border-white/10 flex-shrink-0">
                <div className="flex items-center gap-3 text-lg font-semibold text-white mb-2">
                  <Send className="w-5 h-5 text-green-400" />
                  <div className="flex-1 min-w-0">
                    <div className="text-white">AI Response Sent</div>
                  </div>
                  <Badge className="bg-green-500/20 text-green-300 border-green-500/30">
                    Successfully Sent
                  </Badge>
                </div>
                <p className="text-sm text-gray-300">
                  <span className="font-medium">To:</span> {selectedConversation.to} â€¢
                  <span className="font-medium"> Subject:</span> Re: {selectedConversation.originalSubject}
                </p>
              </div>
              
              <div className="flex-1 p-6 space-y-6 overflow-y-auto">
                <div className="bg-green-500/5 rounded-xl p-6 border border-green-500/20">
                  <p className="text-sm font-medium text-green-300 mb-4 flex items-center gap-2">
                    <Send className="w-4 h-4" />
                    AI Response Sent:
                  </p>
                  <div className="text-sm text-green-100 leading-relaxed custom-scrollbar">
                    {selectedConversation.response}
                  </div>
                </div>

                <div className="bg-green-500/10 border border-green-500/20 rounded-xl p-6">
                  <div className="flex items-start gap-4">
                    <div className="w-10 h-10 bg-green-500/30 rounded-full flex items-center justify-center flex-shrink-0">
                      <CheckCircle className="w-5 h-5 text-green-300" />
                    </div>
                    <div className="flex-1">
                      <p className="text-base font-medium text-green-200 mb-2">Response Delivered Successfully</p>
                      <p className="text-sm text-green-300 leading-relaxed">
                        Your AI-generated response has been sent to the customer. The conversation will continue to be monitored for any replies.
                      </p>
                    </div>
                  </div>
                </div>

                <div className="bg-[#161B22] rounded-xl p-4 space-y-3 border border-gray-800">
                  <h4 className="font-medium text-white">Response Details</h4>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
                    <div>
                      <span className="font-medium text-gray-400">Sent to:</span>
                      <p className="text-gray-300">{selectedConversation.to}</p>
                    </div>
                    <div>
                      <span className="font-medium text-gray-400">Sent at:</span>
                      <p className="text-gray-300">{selectedConversation.sentTime}</p>
                    </div>
                    <div>
                      <span className="font-medium text-gray-400">Response ID:</span>
                      <p className="text-gray-300 font-mono text-xs">{selectedConversation.id}</p>
                    </div>
                    <div>
                      <span className="font-medium text-gray-400">Status:</span>
                      <p className="text-green-300 font-medium">âœ“ Delivered</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          ) : (
            <div className="bg-[#161B22] rounded-xl border border-gray-800 h-[calc(100vh-480px)] min-h-[600px] flex flex-col">
              <div className="flex-1 p-16 text-center flex flex-col items-center justify-center">
                <div className="w-24 h-24 mx-auto mb-8 bg-[#161B22] rounded-full flex items-center justify-center">
                  <MessageSquare className="w-12 h-12 text-gray-400" />
                </div>
                <h3 className="text-xl font-semibold text-white mb-3">Select a conversation</h3>
                <p className="text-gray-300 mb-8 max-w-md leading-relaxed">
                  Choose an email from the {activeEmailView} to view details and manage responses.
                </p>
                <div className="grid grid-cols-1 gap-3 text-sm text-gray-400 max-w-sm">
                  <div className="flex items-center gap-3">
                    <CheckCircle className="w-4 h-4 text-green-400 flex-shrink-0" />
                    <span>Preview AI responses before sending</span>
                  </div>
                  <div className="flex items-center gap-3">
                    <CheckCircle className="w-4 h-4 text-green-400 flex-shrink-0" />
                    <span>Track all sent responses</span>
                  </div>
                  <div className="flex items-center gap-3">
                    <CheckCircle className="w-4 h-4 text-green-400 flex-shrink-0" />
                    <span>Real-time conversation monitoring</span>
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );

  const _deadJSX = () => null;
  // Keep AutomationTab exactly the same
  const AutomationTab = () => (
    <div className="space-y-6">
      {/* ALL AUTOMATION TAB CONTENT REMAINS EXACTLY THE SAME */}
      <div className="bg-[#161B22] rounded-xl border border-gray-800 p-6">
        <div className="flex items-center gap-2 mb-4">
          <Filter className="w-5 h-5 text-blue-400" />
          <h3 className="text-lg font-semibold text-white">Email Filtering</h3>
        </div>
        <p className="text-gray-300 mb-6">Automatically filter emails to focus on real inquiries</p>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {[
            { key: 'autoArchiveSpam', label: 'Auto-Archive Spam', desc: 'Automatically filter out spam emails' },
            { key: 'blockMassEmails', label: 'Block Mass Emails', desc: 'Filter newsletters and promotional emails' },
            { key: 'personalOnly', label: 'Personal Only', desc: 'Only process emails that appear personal' },
            { key: 'skipAutoGenerated', label: 'Skip Auto-Generated', desc: 'Ignore automated system emails' }
          ].map(({ key, label, desc }) => (
            <div key={`filter-${key}`} className="flex items-start space-x-3 p-3 bg-white/5 border border-white/10 rounded-lg">
              <input
                type="checkbox"
                checked={automationSettings.emailFiltering[key]}
                onChange={(e) => handleEmailFilteringChange(key, e.target.checked)}
                className="mt-1 rounded border-gray-700 bg-[#161B22] text-blue-500 focus:ring-blue-500"
              />
              <div>
                <label className="text-sm font-medium text-white">{label}</label>
                <p className="text-xs text-gray-400">{desc}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Keep all business rules sections */}
      <div className="bg-[#161B22] rounded-xl border border-gray-800 p-6">
        <div className="flex items-center gap-2 mb-4">
          <Shield className="w-5 h-5 text-blue-400" />
          <h3 className="text-lg font-semibold text-white">Business Rules</h3>
        </div>
        <p className="text-gray-300 mb-6">Control which emails get AI responses</p>
        <div className="space-y-6">
          <div>
            <label className="block text-sm font-medium mb-2 text-gray-300">Blacklist (Never respond to these)</label>
            <div className="space-y-2">
              <div className="flex flex-wrap gap-2">
                {automationSettings.businessRules.blacklist.map((item, index) => (
                  <div 
                    key={`blacklist-${index}-${item}`}
                    onClick={() => removeFromBlacklist(index)}
                    className="cursor-pointer flex items-center gap-1 px-3 py-1 rounded-full bg-red-500/20 border border-red-500/30 text-red-300 hover:bg-red-500/30 transition-colors"
                  >
                    {item}
                    <X className="w-3 h-3" />
                  </div>
                ))}
              </div>
              <div className="flex gap-2">
                <Input
                  value={newBlacklistItem}
                  onChange={(e) => setNewBlacklistItem(e.target.value)}
                  placeholder="Add email or domain to blacklist"
                  onKeyPress={(e) => e.key === 'Enter' && addToBlacklist()}
                  className="bg-[#0D1117] border-gray-800 text-white placeholder:text-gray-600 focus:border-blue-500"
                />
                <Button onClick={addToBlacklist} size="sm" className="bg-red-600 hover:bg-red-700 text-white">Add</Button>
              </div>
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium mb-2 text-gray-300">Whitelist (Always respond to these)</label>
            <div className="space-y-2">
              <div className="flex flex-wrap gap-2">
                {automationSettings.businessRules.whitelist.map((item, index) => (
                  <div 
                    key={`whitelist-${index}-${item}`}
                    onClick={() => removeFromWhitelist(index)}
                    className="cursor-pointer flex items-center gap-1 px-3 py-1 rounded-full bg-green-500/20 border border-green-500/30 text-green-300 hover:bg-green-500/30 transition-colors"
                  >
                    {item}
                    <X className="w-3 h-3" />
                  </div>
                ))}
              </div>
              <div className="flex gap-2">
                <Input
                  value={newWhitelistItem}
                  onChange={(e) => setNewWhitelistItem(e.target.value)}
                  placeholder="Add email or domain to whitelist"
                  onKeyPress={(e) => e.key === 'Enter' && addToWhitelist()}
                  className="bg-[#0D1117] border-gray-800 text-white placeholder:text-gray-600 focus:border-blue-500"
                />
                <Button onClick={addToWhitelist} size="sm" className="bg-green-600 hover:bg-green-700 text-white">Add</Button>
              </div>
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium mb-2 text-gray-300">Priority Keywords (Respond to these first)</label>
            <div className="space-y-2">
              <div className="flex flex-wrap gap-2">
                {automationSettings.businessRules.customKeywords.map((keyword, index) => (
                  <div 
                    key={`custom-keyword-${index}-${keyword}`}
                    onClick={() => removeCustomKeyword(index)}
                    className="cursor-pointer flex items-center gap-1 px-3 py-1 rounded-full bg-[#161B22] border border-gray-700 text-gray-300 hover:bg-violet-500/10 hover:border-violet-500/30 transition-colors"
                  >
                    {keyword}
                    <X className="w-3 h-3" />
                  </div>
                ))}
              </div>
              <div className="flex gap-2">
                <Input
                  value={newCustomKeyword}
                  onChange={(e) => setNewCustomKeyword(e.target.value)}
                  placeholder="Add priority keyword"
                  onKeyPress={(e) => e.key === 'Enter' && addCustomKeyword()}
                  className="bg-[#0D1117] border-gray-800 text-white placeholder:text-gray-600 focus:border-blue-500"
                />
                <Button onClick={addCustomKeyword} size="sm" className="bg-purple-600 hover:bg-purple-700 text-white">Add</Button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="flex justify-end">
        <Button 
          onClick={saveAllSettings} 
          disabled={saving} 
          className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white"
        >
          {saving ? <RefreshCw className="w-4 h-4 animate-spin" /> : <CheckCircle className="w-4 h-4" />}
          Save Automation Settings
        </Button>
      </div>
    </div>
  );

  if (loading) {
    return (
      <div className="flex items-center justify-center h-full min-h-[400px]">
        <div className="text-center">
          <div className="w-8 h-8 border-2 border-violet-500 border-t-transparent rounded-full animate-spin mx-auto mb-3" />
          <p className="text-gray-400 text-sm">Loading Email...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="p-8 space-y-6">

      {/* Page Header */}
      <div>
        <h1 className="text-2xl font-bold text-white">Email</h1>
        <p className="text-sm text-gray-500 mt-0.5">Gmail automation with smart AI responses and filtering</p>
      </div>

      {/* Internal Tabs */}
      <div>
        <div className="border-b border-gray-800">
          <nav className="-mb-px flex space-x-6">
            {tabs.map(tab => {
              const Icon = tab.icon;
              return (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={`whitespace-nowrap py-2.5 px-1 border-b-2 font-medium text-sm transition-colors ${
                    activeTab === tab.id
                      ? 'border-violet-500 text-violet-400'
                      : 'border-transparent text-gray-500 hover:text-gray-300 hover:border-gray-600'
                  }`}
                >
                  <div className="flex items-center gap-2">
                    <Icon className="w-4 h-4" />
                    {tab.label}
                  </div>
                </button>
              );
            })}
          </nav>
        </div>
        <div className="mt-2">
          <p className="text-sm text-gray-500">
            {tabs.find(tab => tab.id === activeTab)?.description}
          </p>
        </div>
      </div>

      <div className="tab-content">
        {activeTab === 'dashboard' && <DashboardTab />}

        {activeTab === 'automation' && <AutomationTab />}
        {activeTab === 'connections' && <ConnectionsTab />}
      </div>
    </div>
  );
}
